apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f k8s/docker-compose.yml -o k8s/base
    kompose.image-pull-secret: regcred
    kompose.service.expose: petclinic.ftepe.com
    kompose.service.type: nodeport
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f k8s/docker-compose.yml -o k8s/base
        kompose.image-pull-secret: regcred
        kompose.service.expose: petclinic.ftepe.com
        kompose.service.type: nodeport
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
        - image: IMAGE_TAG_API_GATEWAY
          name: api-gateway
          ports:
            - containerPort: 8080
          resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always

      initContainers:
      - name: init-discovery-server
        image: busybox
        command: ['sh', '-c', 'until nc -z discovery-server:8761; do echo waiting for discovery-server; sleep 2; done;']
status: {}
