apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f k8s/docker-compose.yml -o k8s/base
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-server
  name: mysql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f k8s/docker-compose.yml -o k8s/base
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-server
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: petclinic
            - name: MYSQL_ROOT_PASSWORD
              value: petclinic
          image: mysql:5.7.8
          name: mysql-server
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always

      initContainers:
      - name: init-discovery-server
        image: busybox
        command: ['sh', '-c', 'until nc -z discovery-server:8761; do echo waiting for discovery-server; sleep 2; done;']

status: {}
