apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f k8s/docker-compose.yml -o k8s/base
    kompose.image-pull-secret: regcred
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: vets-service
  name: vets-service
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: vets-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f k8s/docker-compose.yml -o k8s/base
        kompose.image-pull-secret: regcred
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: vets-service
    spec:
      containers:
        - image: IMAGE_TAG_VETS_SERVICE
          name: vets-service
          ports:
            - containerPort: 8083
          resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always

      initContainers:
      - name: init-discovery-server
        image: busybox
        command: ['sh', '-c', 'until nc -z discovery-server:8761; do echo waiting for discovery-server; sleep 2; done;']
status: {}
